2023-02-21 08:50:42,776 DEBUG    root            Loaded Command Group: ['gcloud', 'projects']
2023-02-21 08:50:42,777 DEBUG    root            Loaded Command Group: ['gcloud', 'projects', 'describe']
2023-02-21 08:50:42,778 DEBUG    root            Running [gcloud.projects.describe] with arguments: [--account: "wongshennan@gmail.com", --configuration: "default", --format: "value(name)", PROJECT_ID_OR_NUMBER: "test"]
2023-02-21 08:50:42,791 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2023-02-21 08:50:44,002 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "GET /v1/projects/test?alt=json HTTP/1.1" 403 None
2023-02-21 08:50:44,009 DEBUG    root            (gcloud.projects.describe) User [wongshennan@gmail.com] does not have permission to access projects instance [test] (or it may not exist): The caller does not have permission
Traceback (most recent call last):
  File "/Users/wongshennan/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/wongshennan/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/Users/wongshennan/google-cloud-sdk/lib/surface/projects/describe.py", line 51, in Run
    return projects_api.Get(project_ref)
  File "/Users/wongshennan/google-cloud-sdk/lib/googlecloudsdk/api_lib/cloudresourcemanager/projects_api.py", line 129, in Get
    return client.projects.Get(
  File "/Users/wongshennan/google-cloud-sdk/lib/googlecloudsdk/third_party/apis/cloudresourcemanager/v1/cloudresourcemanager_v1_client.py", line 758, in Get
    return self._RunMethod(
  File "/Users/wongshennan/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 737, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/Users/wongshennan/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 743, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/Users/wongshennan/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 609, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpForbiddenError: HttpError accessing <https://cloudresourcemanager.googleapis.com/v1/projects/test?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Tue, 21 Feb 2023 00:50:43 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'server-timing': 'gfet4t7; dur=1086', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'transfer-encoding': 'chunked', 'status': 403}>, content <{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
>
2023-02-21 08:50:44,012 ERROR    root            (gcloud.projects.describe) User [wongshennan@gmail.com] does not have permission to access projects instance [test] (or it may not exist): The caller does not have permission
