2023-02-26 21:59:16,686 DEBUG    root            Loaded Command Group: ['gcloud', 'auth']
2023-02-26 21:59:16,688 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'list']
2023-02-26 21:59:16,690 DEBUG    root            Running [gcloud.auth.list] with arguments: [--filter: "status=ACTIVE", --format: "value(account)", --quiet: "True", --verbosity: "warning"]
2023-02-26 21:59:17,196 DEBUG    root            Chosen display Format:    table[title='Credentialed Accounts'](
        status.yesno(yes='*', no=''):label=ACTIVE,
        account
    ) value(account)
2023-02-26 21:59:17,200 INFO     root            Display format: "    table[title='Credentialed Accounts'](
        status.yesno(yes='*', no=''):label=ACTIVE,
        account
    ) value(account)"
2023-02-26 21:59:17,203 INFO     ___FILE_ONLY___ wongshennan@gmail.com

2023-02-26 21:59:17,205 DEBUG    root            Checking for updates...
2023-02-26 21:59:17,227 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): dl.google.com:443
2023-02-26 21:59:22,289 DEBUG    root            Failed to perform update check.
Traceback (most recent call last):
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/wongshennan/opt/anaconda3/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/Users/wongshennan/opt/anaconda3/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/Users/wongshennan/opt/anaconda3/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/wongshennan/opt/anaconda3/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Users/wongshennan/opt/anaconda3/lib/python3.9/ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/wongshennan/opt/anaconda3/lib/python3.9/ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='dl.google.com', port=443): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/gcloud_main.py", line 61, in UpdateCheck
    update_manager.UpdateManager.PerformUpdateCheck(command_path=command_path)
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 304, in PerformUpdateCheck
    manager._PerformUpdateCheck(command_path, force=force)
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 738, in _PerformUpdateCheck
    (_, diff) = self._GetStateAndDiff(
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 692, in _GetStateAndDiff
    latest_snapshot = self._GetLatestSnapshot(version=version,
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 675, in _GetLatestSnapshot
    return snapshots.ComponentSnapshot.FromURLs(
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/updater/snapshots.py", line 175, in FromURLs
    data = [
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/updater/snapshots.py", line 176, in <listcomp>
    (ComponentSnapshot._DictFromURL(
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/updater/snapshots.py", line 200, in _DictFromURL
    response = installers.MakeRequest(url, command_path)
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/updater/installers.py", line 114, in MakeRequest
    return _RawRequest(url, headers=headers, timeout=timeout)
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/updater/installers.py", line 162, in _RawRequest
    return retryer.RetryOnException(
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 201, in RetryOnException
    exceptions.reraise(exc_info[1], tb=exc_info[2])
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/exceptions.py", line 146, in reraise
    six.reraise(type(exc_value), exc_value, tb)
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/six/__init__.py", line 719, in reraise
    raise value
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 182, in TryFunc
    return func(*args, **kwargs), None
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/updater/installers.py", line 192, in _ExecuteRequestAndRaiseExceptions
    response = requests_session.get(
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/transport.py", line 260, in WrappedRequest
    response = orig_request(*modified_args, **modified_kwargs)
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/requests.py", line 246, in WrappedRequest
    return orig_request_method(*args, **kwargs)
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wongshennan/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='dl.google.com', port=443): Read timed out. (read timeout=3)
